### ISSUE TITLE
Re-subscribe to Azure

### ISSUE THREAD

**Issue by haydenmurdock** [PresidioIdentity/.github#16]
Acceptance criteria: 

- [ ] Our azure products continue to be accessible after re-subscribing to azure 

Tasks

- [ ] re-subscribe using card provided by Dennis 

- [ ] Double check that Demo is working and accessible.

**Comment by tommylau-presidio-identity** [comment]
Issues with Azure processing our payment. Demo will be reployed with new env instead.
